feat: added mongoose schemas and models
PoMaKoM-RSTeam/send-to-telegram-back pull request #17
Opened 2022-01-17 20:45 UTC by AndrewMakarevich

2022-01-17 20:47 UTC, PoMaKoM requested changes

2022-01-17 20:47 UTC, PoMaKoM commented on package.json
> +    "demon": "nodemon src/index.ts",
`"demon": "nodemon src/index.ts",` - удалить!

2022-01-17 20:47 UTC, PoMaKoM commented on package.json
> +    "dotenv": "^12.0.4",
Убрать пока. Возможно позже добавим.

(убрать через `npm remove`)

2022-01-19 19:12 UTC, AlexXG0152 approved these changes

2022-01-20 08:33 UTC, AndrewMakarevich commented on package.json
> +    "dotenv": "^12.0.4",
Удалил

2022-01-20 08:33 UTC, AndrewMakarevich commented on package.json
> +    "demon": "nodemon src/index.ts",
Удалил

2022-01-26 22:33 UTC, PoMaKoM approved these changes

2022-01-27 07:43 UTC, merged