feature: add README.md
PoMaKoM-RSTeam/send-to-telegram-back pull request #2
Opened 2022-01-08 09:44 UTC by AlexXG0152

2022-01-08 09:46 UTC, AlexXG0152 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Добавить README файл](https://trello.com/c/qdnsLWrT/5-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-readme-%D1%84%D0%B0%D0%B9%D0%BB)

2022-01-10 16:43 UTC, PoMaKoM requested changes

2022-01-10 16:43 UTC, PoMaKoM commented on README.md
> +![GitHub commit activity](https://img.shields.io/github/commit-activity/y/PoMaKoM-RSTeam/send-to-telegram-front?style=for-the-badge)
Хитро скопировано))) 

`send-to-telegram-front` заменить на `send-to-telegram-back`

2022-01-10 17:59 UTC, PoMaKoM requested changes

2022-01-10 17:59 UTC, PoMaKoM commented on README.md
> +![GitHub](https://img.shields.io/github/license/PoMaKoM-RSTeam/send-to-telegram-front?style=for-the-badge)
Это что за покемон?

2022-01-10 18:00 UTC, PoMaKoM approved these changes

2022-01-10 18:00 UTC, merged